services:
  db:
    image: 'mysql:latest'
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=cooksnap_database
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
    ports:
      - 3306:3306
    restart: unless-stopped



