services:
  db:
    image: 'mysql:latest'
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=cooksnap_database
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
    ports:
      - 3306:3306
    restart: unless-stopped
  main-server:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cooksnap_database
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev
    



